// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Shared.ViewModel;

namespace MasterDetail
{
	public partial class AccountListViewController : UIViewController
	{
		AccountViewModel viewModel = new AccountViewModel();
		public AccountListViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			AccountListTableViewOutlet.Source = new AccountTableSources(viewModel.AccountItems ());
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			if (segue.Identifier == "AccountListSegue") {
				var nav = segue.DestinationViewController as AccountViewController;
				if (nav != null) {
					var rowPath = AccountListTableViewOutlet.IndexPathForSelectedRow;
					var source = AccountListTableViewOutlet.Source as AccountTableSources;
					var item = source.GetItem (rowPath.Row);

					nav.SetData (this, item);
				}
			}
		}
	}
}
